# Netlify configuration for Next.js 14 App Router project
# Keep minimal config: the Next.js Netlify Runtime handles routing and assets.

[build]
  command = "npm run build"
  # Do not set publish when using the Next.js Netlify Runtime

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Enable the Next.js runtime (SSR/ISR) on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"
